; PlatformIO - EXTI Rising/Falling
[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = arduino
upload_protocol = stlink
upload_flags = -c set CPUTAPID 0x2ba01477
monitor_speed = 115200
lib_deps = 
    adafruit/Adafruit SSD1306
    adafruit/Adafruit GFX Library